### ISSUE TITLE
kria: meta-sequencing

### ISSUE THREAD

**Issue by tehn** [monome/ansible#22]
like ww series mode

- [x] sequencer meta-steps assigned to one of 16 patterns
- [x] number of clocks per meta-step
- [x] on/off
- [x] cue-sync
- [x] meta-loop set
- [x] cue clock

**Comment by tehn** [comment]
needs testing and docs

f6821e7..0c87f5b

**Comment by tehn** [comment]
bottom-right (pattern) held down = cue

top row is patterns
meta-clock is row below this (key in this row is clock count, mod-time for division)

row above bottom row = meta step length. cue + this row toggles meta mode. key in this row edits step length for selected meta step.

four rows in the middle = meta step. push position to edit (select pattern on top row). cue + push to set next position (jump). mod-loop to select loop (two-touch, like the rest of kria).

meta mode can continue while editing tr/note/etc data but it's super confusing because the view changes-- showing is the currently playing pattern.

**Comment by tehn** [comment]
tested fine so far.
